spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test-client-id
            client-secret: test-client-secret
            scope:
              - openid
              - profile
              - email
              - https://www.googleapis.com/auth/calendar

jwt:
  secret: test-secret-key-for-testing-minimum-256-bits-required-for-hmac-sha
  expiration: 86400000
  refresh-expiration: 604800000

google:
  calendar:
    application-name: Task Management API Test
    credentials-file-path: classpath:test-google-credentials.json

app:
  cors:
    allowed-origins: http://localhost:3000
  oauth2:
    authorized-redirect-uris:
      - http://localhost:3000/oauth2/redirect

logging:
  level:
    root: INFO
    com.taskmanagement: DEBUG